### ISSUE TITLE
dotnet deb install command fail

### ISSUE THREAD

**Issue by pyking-wang** [quamotion/dotnet-packaging#238]
Just tried to use your utility.
dotnet tool install --global dotnet-deb command was successful.
But now I am stuck at:
C:\GIT\ProjectFolder>dotnet deb install
Unhandled exception. System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
at Dotnet.Packaging.PackagingRunner..ctor(String outputName, String msbuildTarget, String commandName) in /__w/1/s/dotnet-rpm/PackagingRunner.cs:line 29
at Dotnet.Packaging.Program.Main(String[] args) in /__w/1/s/dotnet-deb/Program.cs:line 9
I tried to figure out what's happenning but failed.
Defintely I have both Microsoft Visual Studio 2022 with MSBuild installed.
Could anyone help me wth this issue? Thanks!

**Comment by pyking-wang** [comment]
You can refer to # 233.
